spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/deptManager
    username: deptManager
    password: deptManager
    initialization-mode: embedded
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
        temp:
          use_jdbc_metadata_defaults: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop

logging:
  level:
    org.springframework.web: debug
server:
  port: 8080
  error:
    include-stacktrace: never
jwt:
  secret: 1c9d384a-d6b6-496f-8e3a-a5f044631d91
